namespace Telnet
{
    public enum eTelnetOption : byte
    {
        TransmitBinary = 0,
        Echo = 1,
        Reconnection = 2,
        SuppressGoAhead = 3,
        ApproxMessageSizeNegotiation = 4,
        Status = 5,
        TimingMark = 6,
        RemoteControlledTransandEcho = 7,
        OutputLineWidth = 8,
        OutputPageSize = 9,
        NegotiateAboutOutputCarriageReturnDisposition = 10,
        NegotiateAboutOutputHorizontalTabstops = 11,
        NegotiateAboutOutputHorizontalTabDisposition = 12,
        NegotiateAboutOutputFormfeedDisposition = 13,
        NegotiateAboutVerticalTabstops = 14,
        NegotiateAboutOutputVertcialTabDisposition = 15,
        NegotiateAboutOutputLinefeedDisposition = 16,
        ExtendedASCII = 17,
        Logout = 18,
        ByteMacro = 19,
        DataEntryTerminal = 20,
        SUPDUP = 21,
        SUPDUPOutput = 22,
        SendLocation = 23,
        TerminalType = 24,
        EndofRecord = 25,
        TACACSUserIdentification = 26,
        OutputMarking = 27,
        TTYLOCTerminalLocationNumber = 28,
        Telnet3270Regime = 29,
        X3PAD = 30,
        NegotiateAboutWindowSize = 31,
        TerminalSpeed = 32,
        RemoteFlowControl = 33,
        Linemode = 34,
        XDisplayLocation = 35,
        Environment = 36,
        Authentication = 37,
        EncryptionOption = 38,
        NewEnvironment = 39,
        TN3270E = 40,
        XAUTH = 41,
        CHARSET = 42,
        TelnetRemoteSerialPort = 43,
        ComPortControl = 44,
        TelnetSuppressLocalEcho = 45,
        TelnetStartTLS = 46,
        KERMIT = 47,
        SendURL = 48,
        FORWARD_X = 49,
        TELOPTPRAGMALOGON = 138,
        TELOPTSSPILOGON = 139,
        TELOPTPRAGMAHEARTBEAT = 140,
        ExtendedOptionsList = 255
    }
}